---
title: "Jonathan Cervas"
description: |
  Postdoctoral Fellow, Carnegie Mellon University
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

Jonathan began at Carnegie Mellon University after receiving his PhD in Political Science from the University of California, Irvine. His Bachelor’s degree (also in political science) is from the University of Nevada, Las Vegas. His dissertation is a historical, quantitative look at the Electoral College and its consequences.

In 2021, Jonathan served as the redistricting consultant for the Pennsylvania Legislative Reapportionment Commission. He was appointed to that position by a vote of the commission. The final plan received a bi-partisan vote and was upheld unanimously by the Pennsylvania Supreme Court. You can see these plans here. He served as Special Master for the state of New York in 2022 [Harkenrider v. Hochel (2022)] and drew the state's 26 Congressional Districts and 63 state Senate districts. He has also served as the assistant to a federal court Special Master in drawing remedial maps in three redistricting cases involving minority rights. The first of these was Navajo Nation et al v. San Juan County,Utah in 2017; followed in 2018-19 by Bethune-Hill et al v. State Board of Election,which involved the redrawing of one quarter of the districts in Virginia's legislative districts in the House Of Delegates; and in 2019-20, he worked on Wright v. Sumter County Board of Elections, a case involving school districts in a small Georgia County where former President Jimmy Carter makes his home. He has published several articles on both the elections and gerrymandering, and is a Research Associate at the Electoral Innovation Lab.